### ISSUE TITLE
Usar por defecto un determinado SRS

### ISSUE THREAD

**Issue by cjgb** [rOpenSpain/CatastRo#5]
Creo que sería conveniente no obligar al usuario a tener que elegir un sistema de coordenadas concreto. Podría ponerse por defecto el EPSG:4258 (que creo que es el oficial de España) o el que usa Google Maps (EPSG:3857, creo), tal vez con alias. Por ejemplo:

1. Por defecto, se usa uno de los dos anteriores (¿cuál?).
2. Se pueden crear alias (SRS = "google" sería el EPSG:3857; SRS = "oficial", sería el EPSG:4258). 
3. Finalmente, el usuario puede elegir el que quiera.

**Comment by DelgadoPanadero** [comment]
Ahora mismo no es necesario elegir un sistema de coordenadas (SRS) para ninguna de las funciones. En caso de que el usuario no especifique ninguna, las funciones `get_rc` y `near_rc`  realizan la consulta sobre todos los SRS posibles, mientras que la función `get_coor` devuelve las coordenadas en el SRS en el que fue almacenado.

No obstante la idea del punto 2 es bastante interesante y se podría incluir a la hora de especificar el SRS.
